Added LIS_OUTCOME_SERVICE_URL to launch call.
oat-sa/extension-tao-lti-consumer pull request #30
Opened 2019-09-10 14:36 UTC by julien-sebire

Actually does what the NEX-319 ticket asked for.

2019-09-12 09:29 UTC, siwane requested changes

2019-09-12 09:29 UTC, siwane commented on model/delivery/container/LtiDeliveryContainer.php
> +            LtiLaunchData::LIS_OUTCOME_SERVICE_URL => $outcomeServiceUrl,
This constant comes with taoLti : 10.5.1, please update dependency to include this verison

2019-10-18 11:57 UTC, julien-sebire commented on model/delivery/container/LtiDeliveryContainer.php
> +            LtiLaunchData::LIS_OUTCOME_SERVICE_URL => $outcomeServiceUrl,
Fixed.

2019-10-18 12:03 UTC, boajer approved these changes
Nice job!

2019-11-21 15:35 UTC, boajer commented
@mike-ionut-mihai-sandu-tao  @julien-sebire  I've merged develop into this branch, looks like there are almost no chages left. 
Is it still needed ?

2019-11-21 15:36 UTC, mike-ionut-mihai-sandu-tao reviewed
let's please check if this is still required and either merge or close this pr, also let's check the version from manifest

2020-01-13 13:28 UTC, closed without merging