Feature/nex 457/log verbosity imporved
oat-sa/extension-tao-lti-consumer pull request #31
Opened 2019-10-08 13:59 UTC by boajer

https://oat-sa.atlassian.net/browse/NEX-457

2019-10-08 15:21 UTC, mike-ionut-mihai-sandu-tao requested changes

2019-10-08 15:21 UTC, mike-ionut-mihai-sandu-tao commented on model/FilteringHelper.php
> +}
\n

2019-10-08 15:21 UTC, mike-ionut-mihai-sandu-tao commented on model/FilteringHelper.php
> +    public static function anonymize($incomingData, array $blackList)
does this need to be static?

2019-10-08 15:21 UTC, mike-ionut-mihai-sandu-tao commented on model/FilteringHelper.php
> +
can be removed

2019-10-08 15:21 UTC, mike-ionut-mihai-sandu-tao commented on model/delivery/container/LtiDeliveryContainer.php
> +        $this->logDebug(sprintf('** taoLtiConsumer: preparing http call :: to the %s, with payload %s **', $ltiUrl, json_encode(FilteringHelper::anonymize($data, ['oauth_consumer_key']))));
debug or info ?

2019-10-08 15:21 UTC, mike-ionut-mihai-sandu-tao commented on model/delivery/container/LtiDeliveryContainer.php
> +        $this->logDebug(sprintf('** taoLtiConsumer: preparing http call :: to the %s, with payload %s **', $ltiUrl, json_encode(FilteringHelper::anonymize($data, ['oauth_consumer_key']))));
can you please split it into multiple rows
```
        $this->logDebug(
            sprintf('** taoLtiConsumer: preparing http call :: to the %s, with payload %s **',
                    $ltiUrl,
                    json_encode(FilteringHelper::anonymize($data, ['oauth_consumer_key'])))
        );
```

2019-10-08 15:21 UTC, mike-ionut-mihai-sandu-tao commented on model/delivery/container/LtiDeliveryContainer.php
> +        $this->logDebug(sprintf('** taoLtiConsumer: preparing http call :: to the %s, with payload %s **', $ltiUrl, json_encode(FilteringHelper::anonymize($data, ['oauth_consumer_key']))));
can we use DI  instead of calling a static function? (if possible)

2019-10-08 15:21 UTC, mike-ionut-mihai-sandu-tao commented on model/FilteringHelper.php
> +class FilteringHelper
AnonymizerHelper? for me, it does not sound the best  FilteringHelper with `anonymize` method what do you think

2019-10-08 15:21 UTC, mike-ionut-mihai-sandu-tao commented on model/FilteringHelper.php
> +class FilteringHelper
no tests for this class :(

2019-10-08 15:21 UTC, mike-ionut-mihai-sandu-tao commented on model/FilteringHelper.php
> +                if (in_array($key, $blackList, true)) {
i would use also trim on the key here: 
e.g. : 
```
'oauth_consumer_key ' => 'some string',
```
will not be processed

2019-10-09 07:29 UTC, boajer commented on model/delivery/container/LtiDeliveryContainer.php
> +        $this->logDebug(sprintf('** taoLtiConsumer: preparing http call :: to the %s, with payload %s **', $ltiUrl, json_encode(FilteringHelper::anonymize($data, ['oauth_consumer_key']))));
as per Task AC - debug, as all other http communication related log entries

2019-10-10 09:23 UTC, mike-ionut-mihai-sandu-tao approved these changes
nice job!

2019-10-10 10:10 UTC, merged